<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddToCart</name>
   <tag></tag>
   <elementGuidId>4211a3f1-f691-417b-b153-a972abab8ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Adicionar ao carrinho' or . = 'Adicionar ao carrinho')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.add-to-cart__button.button--primary.button--lg.button--red.button.add-to-cart__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42735438-fa21-48eb-9cd2-3ddef70ffdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-to-cart__button button--primary button--lg button--red button add-to-cart__button</value>
      <webElementGuid>7dd1cb29-2c34-481b-a605-42a7050f3d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54ea9b9d-c595-4373-add1-705e61615e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adicionar ao carrinho</value>
      <webElementGuid>0ea68589-0662-4195-80e3-5042fa82347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[1]/div[1]/div[10]/div[1]/section[@class=&quot;product-heading&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;product-heading__main-container&quot;]/div[@class=&quot;product-heading__right-container&quot;]/div[@class=&quot;buy-box&quot;]/div[2]/div[@class=&quot;badges-container--grid badges-container&quot;]/div[@class=&quot;button-list&quot;]/div[@class=&quot;add-to-cart&quot;]/button[@class=&quot;add-to-cart__button button--primary button--lg button--red button add-to-cart__button&quot;]</value>
      <webElementGuid>b1acfeb7-089b-429d-b976-3c16d4d93e8d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
